//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Aogirishop.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AogirishopEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AogirishopEntities object using the connection string found in the 'AogirishopEntities' section of the application configuration file.
        /// </summary>
        public AogirishopEntities() : base("name=AogirishopEntities", "AogirishopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AogirishopEntities object.
        /// </summary>
        public AogirishopEntities(string connectionString) : base(connectionString, "AogirishopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AogirishopEntities object.
        /// </summary>
        public AogirishopEntities(EntityConnection connection) : base(connection, "AogirishopEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Account> N412_Account
        {
            get
            {
                if ((_N412_Account == null))
                {
                    _N412_Account = base.CreateObjectSet<N412_Account>("N412_Account");
                }
                return _N412_Account;
            }
        }
        private ObjectSet<N412_Account> _N412_Account;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Ads> N412_Ads
        {
            get
            {
                if ((_N412_Ads == null))
                {
                    _N412_Ads = base.CreateObjectSet<N412_Ads>("N412_Ads");
                }
                return _N412_Ads;
            }
        }
        private ObjectSet<N412_Ads> _N412_Ads;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_GroupProduct> N412_GroupProduct
        {
            get
            {
                if ((_N412_GroupProduct == null))
                {
                    _N412_GroupProduct = base.CreateObjectSet<N412_GroupProduct>("N412_GroupProduct");
                }
                return _N412_GroupProduct;
            }
        }
        private ObjectSet<N412_GroupProduct> _N412_GroupProduct;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Menu> N412_Menu
        {
            get
            {
                if ((_N412_Menu == null))
                {
                    _N412_Menu = base.CreateObjectSet<N412_Menu>("N412_Menu");
                }
                return _N412_Menu;
            }
        }
        private ObjectSet<N412_Menu> _N412_Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Order> N412_Order
        {
            get
            {
                if ((_N412_Order == null))
                {
                    _N412_Order = base.CreateObjectSet<N412_Order>("N412_Order");
                }
                return _N412_Order;
            }
        }
        private ObjectSet<N412_Order> _N412_Order;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_OrderDetail> N412_OrderDetail
        {
            get
            {
                if ((_N412_OrderDetail == null))
                {
                    _N412_OrderDetail = base.CreateObjectSet<N412_OrderDetail>("N412_OrderDetail");
                }
                return _N412_OrderDetail;
            }
        }
        private ObjectSet<N412_OrderDetail> _N412_OrderDetail;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Post> N412_Post
        {
            get
            {
                if ((_N412_Post == null))
                {
                    _N412_Post = base.CreateObjectSet<N412_Post>("N412_Post");
                }
                return _N412_Post;
            }
        }
        private ObjectSet<N412_Post> _N412_Post;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<N412_Product> N412_Product
        {
            get
            {
                if ((_N412_Product == null))
                {
                    _N412_Product = base.CreateObjectSet<N412_Product>("N412_Product");
                }
                return _N412_Product;
            }
        }
        private ObjectSet<N412_Product> _N412_Product;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Account EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Account(N412_Account n412_Account)
        {
            base.AddObject("N412_Account", n412_Account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Ads EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Ads(N412_Ads n412_Ads)
        {
            base.AddObject("N412_Ads", n412_Ads);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_GroupProduct EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_GroupProduct(N412_GroupProduct n412_GroupProduct)
        {
            base.AddObject("N412_GroupProduct", n412_GroupProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Menu(N412_Menu n412_Menu)
        {
            base.AddObject("N412_Menu", n412_Menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Order EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Order(N412_Order n412_Order)
        {
            base.AddObject("N412_Order", n412_Order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_OrderDetail EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_OrderDetail(N412_OrderDetail n412_OrderDetail)
        {
            base.AddObject("N412_OrderDetail", n412_OrderDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Post EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Post(N412_Post n412_Post)
        {
            base.AddObject("N412_Post", n412_Post);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the N412_Product EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToN412_Product(N412_Product n412_Product)
        {
            base.AddObject("N412_Product", n412_Product);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Account object.
        /// </summary>
        /// <param name="account_ID">Initial value of the Account_ID property.</param>
        public static N412_Account CreateN412_Account(global::System.Int32 account_ID)
        {
            N412_Account n412_Account = new N412_Account();
            n412_Account.Account_ID = account_ID;
            return n412_Account;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Account_ID
        {
            get
            {
                return _Account_ID;
            }
            set
            {
                if (_Account_ID != value)
                {
                    OnAccount_IDChanging(value);
                    ReportPropertyChanging("Account_ID");
                    _Account_ID = StructuralObject.SetValidValue(value, "Account_ID");
                    ReportPropertyChanged("Account_ID");
                    OnAccount_IDChanged();
                }
            }
        }
        private global::System.Int32 _Account_ID;
        partial void OnAccount_IDChanging(global::System.Int32 value);
        partial void OnAccount_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_FirstName
        {
            get
            {
                return _Account_FirstName;
            }
            set
            {
                OnAccount_FirstNameChanging(value);
                ReportPropertyChanging("Account_FirstName");
                _Account_FirstName = StructuralObject.SetValidValue(value, true, "Account_FirstName");
                ReportPropertyChanged("Account_FirstName");
                OnAccount_FirstNameChanged();
            }
        }
        private global::System.String _Account_FirstName;
        partial void OnAccount_FirstNameChanging(global::System.String value);
        partial void OnAccount_FirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_LastName
        {
            get
            {
                return _Account_LastName;
            }
            set
            {
                OnAccount_LastNameChanging(value);
                ReportPropertyChanging("Account_LastName");
                _Account_LastName = StructuralObject.SetValidValue(value, true, "Account_LastName");
                ReportPropertyChanged("Account_LastName");
                OnAccount_LastNameChanged();
            }
        }
        private global::System.String _Account_LastName;
        partial void OnAccount_LastNameChanging(global::System.String value);
        partial void OnAccount_LastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_Email
        {
            get
            {
                return _Account_Email;
            }
            set
            {
                OnAccount_EmailChanging(value);
                ReportPropertyChanging("Account_Email");
                _Account_Email = StructuralObject.SetValidValue(value, true, "Account_Email");
                ReportPropertyChanged("Account_Email");
                OnAccount_EmailChanged();
            }
        }
        private global::System.String _Account_Email;
        partial void OnAccount_EmailChanging(global::System.String value);
        partial void OnAccount_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_UserName
        {
            get
            {
                return _Account_UserName;
            }
            set
            {
                OnAccount_UserNameChanging(value);
                ReportPropertyChanging("Account_UserName");
                _Account_UserName = StructuralObject.SetValidValue(value, true, "Account_UserName");
                ReportPropertyChanged("Account_UserName");
                OnAccount_UserNameChanged();
            }
        }
        private global::System.String _Account_UserName;
        partial void OnAccount_UserNameChanging(global::System.String value);
        partial void OnAccount_UserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Account_Password
        {
            get
            {
                return _Account_Password;
            }
            set
            {
                OnAccount_PasswordChanging(value);
                ReportPropertyChanging("Account_Password");
                _Account_Password = StructuralObject.SetValidValue(value, true, "Account_Password");
                ReportPropertyChanged("Account_Password");
                OnAccount_PasswordChanged();
            }
        }
        private global::System.String _Account_Password;
        partial void OnAccount_PasswordChanging(global::System.String value);
        partial void OnAccount_PasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Account_Rule
        {
            get
            {
                return _Account_Rule;
            }
            set
            {
                OnAccount_RuleChanging(value);
                ReportPropertyChanging("Account_Rule");
                _Account_Rule = StructuralObject.SetValidValue(value, "Account_Rule");
                ReportPropertyChanged("Account_Rule");
                OnAccount_RuleChanged();
            }
        }
        private Nullable<global::System.Int32> _Account_Rule;
        partial void OnAccount_RuleChanging(Nullable<global::System.Int32> value);
        partial void OnAccount_RuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Account_Status
        {
            get
            {
                return _Account_Status;
            }
            set
            {
                OnAccount_StatusChanging(value);
                ReportPropertyChanging("Account_Status");
                _Account_Status = StructuralObject.SetValidValue(value, "Account_Status");
                ReportPropertyChanged("Account_Status");
                OnAccount_StatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Account_Status;
        partial void OnAccount_StatusChanging(Nullable<global::System.Int32> value);
        partial void OnAccount_StatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Ads")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Ads : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Ads object.
        /// </summary>
        /// <param name="ads_ID">Initial value of the Ads_ID property.</param>
        public static N412_Ads CreateN412_Ads(global::System.Int32 ads_ID)
        {
            N412_Ads n412_Ads = new N412_Ads();
            n412_Ads.Ads_ID = ads_ID;
            return n412_Ads;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ads_ID
        {
            get
            {
                return _Ads_ID;
            }
            set
            {
                if (_Ads_ID != value)
                {
                    OnAds_IDChanging(value);
                    ReportPropertyChanging("Ads_ID");
                    _Ads_ID = StructuralObject.SetValidValue(value, "Ads_ID");
                    ReportPropertyChanged("Ads_ID");
                    OnAds_IDChanged();
                }
            }
        }
        private global::System.Int32 _Ads_ID;
        partial void OnAds_IDChanging(global::System.Int32 value);
        partial void OnAds_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ads_Title
        {
            get
            {
                return _Ads_Title;
            }
            set
            {
                OnAds_TitleChanging(value);
                ReportPropertyChanging("Ads_Title");
                _Ads_Title = StructuralObject.SetValidValue(value, true, "Ads_Title");
                ReportPropertyChanged("Ads_Title");
                OnAds_TitleChanged();
            }
        }
        private global::System.String _Ads_Title;
        partial void OnAds_TitleChanging(global::System.String value);
        partial void OnAds_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ads_Detail
        {
            get
            {
                return _Ads_Detail;
            }
            set
            {
                OnAds_DetailChanging(value);
                ReportPropertyChanging("Ads_Detail");
                _Ads_Detail = StructuralObject.SetValidValue(value, true, "Ads_Detail");
                ReportPropertyChanged("Ads_Detail");
                OnAds_DetailChanged();
            }
        }
        private global::System.String _Ads_Detail;
        partial void OnAds_DetailChanging(global::System.String value);
        partial void OnAds_DetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ads_Positon
        {
            get
            {
                return _Ads_Positon;
            }
            set
            {
                OnAds_PositonChanging(value);
                ReportPropertyChanging("Ads_Positon");
                _Ads_Positon = StructuralObject.SetValidValue(value, "Ads_Positon");
                ReportPropertyChanged("Ads_Positon");
                OnAds_PositonChanged();
            }
        }
        private Nullable<global::System.Int32> _Ads_Positon;
        partial void OnAds_PositonChanging(Nullable<global::System.Int32> value);
        partial void OnAds_PositonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ads_STT
        {
            get
            {
                return _Ads_STT;
            }
            set
            {
                OnAds_STTChanging(value);
                ReportPropertyChanging("Ads_STT");
                _Ads_STT = StructuralObject.SetValidValue(value, "Ads_STT");
                ReportPropertyChanged("Ads_STT");
                OnAds_STTChanged();
            }
        }
        private Nullable<global::System.Int32> _Ads_STT;
        partial void OnAds_STTChanging(Nullable<global::System.Int32> value);
        partial void OnAds_STTChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_GroupProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_GroupProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_GroupProduct object.
        /// </summary>
        /// <param name="groupProduct_ID">Initial value of the GroupProduct_ID property.</param>
        public static N412_GroupProduct CreateN412_GroupProduct(global::System.Int32 groupProduct_ID)
        {
            N412_GroupProduct n412_GroupProduct = new N412_GroupProduct();
            n412_GroupProduct.GroupProduct_ID = groupProduct_ID;
            return n412_GroupProduct;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupProduct_ID
        {
            get
            {
                return _GroupProduct_ID;
            }
            set
            {
                if (_GroupProduct_ID != value)
                {
                    OnGroupProduct_IDChanging(value);
                    ReportPropertyChanging("GroupProduct_ID");
                    _GroupProduct_ID = StructuralObject.SetValidValue(value, "GroupProduct_ID");
                    ReportPropertyChanged("GroupProduct_ID");
                    OnGroupProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _GroupProduct_ID;
        partial void OnGroupProduct_IDChanging(global::System.Int32 value);
        partial void OnGroupProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupProduct_Name
        {
            get
            {
                return _GroupProduct_Name;
            }
            set
            {
                OnGroupProduct_NameChanging(value);
                ReportPropertyChanging("GroupProduct_Name");
                _GroupProduct_Name = StructuralObject.SetValidValue(value, true, "GroupProduct_Name");
                ReportPropertyChanged("GroupProduct_Name");
                OnGroupProduct_NameChanged();
            }
        }
        private global::System.String _GroupProduct_Name;
        partial void OnGroupProduct_NameChanging(global::System.String value);
        partial void OnGroupProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupProduct_Image
        {
            get
            {
                return _GroupProduct_Image;
            }
            set
            {
                OnGroupProduct_ImageChanging(value);
                ReportPropertyChanging("GroupProduct_Image");
                _GroupProduct_Image = StructuralObject.SetValidValue(value, true, "GroupProduct_Image");
                ReportPropertyChanged("GroupProduct_Image");
                OnGroupProduct_ImageChanged();
            }
        }
        private global::System.String _GroupProduct_Image;
        partial void OnGroupProduct_ImageChanging(global::System.String value);
        partial void OnGroupProduct_ImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupProduct_Link
        {
            get
            {
                return _GroupProduct_Link;
            }
            set
            {
                OnGroupProduct_LinkChanging(value);
                ReportPropertyChanging("GroupProduct_Link");
                _GroupProduct_Link = StructuralObject.SetValidValue(value, true, "GroupProduct_Link");
                ReportPropertyChanged("GroupProduct_Link");
                OnGroupProduct_LinkChanged();
            }
        }
        private global::System.String _GroupProduct_Link;
        partial void OnGroupProduct_LinkChanging(global::System.String value);
        partial void OnGroupProduct_LinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GroupProduct_STT
        {
            get
            {
                return _GroupProduct_STT;
            }
            set
            {
                OnGroupProduct_STTChanging(value);
                ReportPropertyChanging("GroupProduct_STT");
                _GroupProduct_STT = StructuralObject.SetValidValue(value, "GroupProduct_STT");
                ReportPropertyChanged("GroupProduct_STT");
                OnGroupProduct_STTChanged();
            }
        }
        private Nullable<global::System.Int32> _GroupProduct_STT;
        partial void OnGroupProduct_STTChanging(Nullable<global::System.Int32> value);
        partial void OnGroupProduct_STTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> GroupProduct_Status
        {
            get
            {
                return _GroupProduct_Status;
            }
            set
            {
                OnGroupProduct_StatusChanging(value);
                ReportPropertyChanging("GroupProduct_Status");
                _GroupProduct_Status = StructuralObject.SetValidValue(value, "GroupProduct_Status");
                ReportPropertyChanged("GroupProduct_Status");
                OnGroupProduct_StatusChanged();
            }
        }
        private Nullable<global::System.Boolean> _GroupProduct_Status;
        partial void OnGroupProduct_StatusChanging(Nullable<global::System.Boolean> value);
        partial void OnGroupProduct_StatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Menu")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Menu : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Menu object.
        /// </summary>
        /// <param name="menu_ID">Initial value of the Menu_ID property.</param>
        public static N412_Menu CreateN412_Menu(global::System.Int32 menu_ID)
        {
            N412_Menu n412_Menu = new N412_Menu();
            n412_Menu.Menu_ID = menu_ID;
            return n412_Menu;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Menu_ID
        {
            get
            {
                return _Menu_ID;
            }
            set
            {
                if (_Menu_ID != value)
                {
                    OnMenu_IDChanging(value);
                    ReportPropertyChanging("Menu_ID");
                    _Menu_ID = StructuralObject.SetValidValue(value, "Menu_ID");
                    ReportPropertyChanged("Menu_ID");
                    OnMenu_IDChanged();
                }
            }
        }
        private global::System.Int32 _Menu_ID;
        partial void OnMenu_IDChanging(global::System.Int32 value);
        partial void OnMenu_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Menu_Name
        {
            get
            {
                return _Menu_Name;
            }
            set
            {
                OnMenu_NameChanging(value);
                ReportPropertyChanging("Menu_Name");
                _Menu_Name = StructuralObject.SetValidValue(value, true, "Menu_Name");
                ReportPropertyChanged("Menu_Name");
                OnMenu_NameChanged();
            }
        }
        private global::System.String _Menu_Name;
        partial void OnMenu_NameChanging(global::System.String value);
        partial void OnMenu_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Menu_Position
        {
            get
            {
                return _Menu_Position;
            }
            set
            {
                OnMenu_PositionChanging(value);
                ReportPropertyChanging("Menu_Position");
                _Menu_Position = StructuralObject.SetValidValue(value, "Menu_Position");
                ReportPropertyChanged("Menu_Position");
                OnMenu_PositionChanged();
            }
        }
        private Nullable<global::System.Int32> _Menu_Position;
        partial void OnMenu_PositionChanging(Nullable<global::System.Int32> value);
        partial void OnMenu_PositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Menu_ParentID
        {
            get
            {
                return _Menu_ParentID;
            }
            set
            {
                OnMenu_ParentIDChanging(value);
                ReportPropertyChanging("Menu_ParentID");
                _Menu_ParentID = StructuralObject.SetValidValue(value, "Menu_ParentID");
                ReportPropertyChanged("Menu_ParentID");
                OnMenu_ParentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _Menu_ParentID;
        partial void OnMenu_ParentIDChanging(Nullable<global::System.Int32> value);
        partial void OnMenu_ParentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Menu_Link
        {
            get
            {
                return _Menu_Link;
            }
            set
            {
                OnMenu_LinkChanging(value);
                ReportPropertyChanging("Menu_Link");
                _Menu_Link = StructuralObject.SetValidValue(value, true, "Menu_Link");
                ReportPropertyChanged("Menu_Link");
                OnMenu_LinkChanged();
            }
        }
        private global::System.String _Menu_Link;
        partial void OnMenu_LinkChanging(global::System.String value);
        partial void OnMenu_LinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Menu_Status
        {
            get
            {
                return _Menu_Status;
            }
            set
            {
                OnMenu_StatusChanging(value);
                ReportPropertyChanging("Menu_Status");
                _Menu_Status = StructuralObject.SetValidValue(value, "Menu_Status");
                ReportPropertyChanged("Menu_Status");
                OnMenu_StatusChanged();
            }
        }
        private Nullable<global::System.Int64> _Menu_Status;
        partial void OnMenu_StatusChanging(Nullable<global::System.Int64> value);
        partial void OnMenu_StatusChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Order object.
        /// </summary>
        /// <param name="order_ID">Initial value of the Order_ID property.</param>
        public static N412_Order CreateN412_Order(global::System.Int32 order_ID)
        {
            N412_Order n412_Order = new N412_Order();
            n412_Order.Order_ID = order_ID;
            return n412_Order;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Order_ID
        {
            get
            {
                return _Order_ID;
            }
            set
            {
                if (_Order_ID != value)
                {
                    OnOrder_IDChanging(value);
                    ReportPropertyChanging("Order_ID");
                    _Order_ID = StructuralObject.SetValidValue(value, "Order_ID");
                    ReportPropertyChanged("Order_ID");
                    OnOrder_IDChanged();
                }
            }
        }
        private global::System.Int32 _Order_ID;
        partial void OnOrder_IDChanging(global::System.Int32 value);
        partial void OnOrder_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Order_Name
        {
            get
            {
                return _Order_Name;
            }
            set
            {
                OnOrder_NameChanging(value);
                ReportPropertyChanging("Order_Name");
                _Order_Name = StructuralObject.SetValidValue(value, true, "Order_Name");
                ReportPropertyChanged("Order_Name");
                OnOrder_NameChanged();
            }
        }
        private global::System.String _Order_Name;
        partial void OnOrder_NameChanging(global::System.String value);
        partial void OnOrder_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Order_Customer
        {
            get
            {
                return _Order_Customer;
            }
            set
            {
                OnOrder_CustomerChanging(value);
                ReportPropertyChanging("Order_Customer");
                _Order_Customer = StructuralObject.SetValidValue(value, true, "Order_Customer");
                ReportPropertyChanged("Order_Customer");
                OnOrder_CustomerChanged();
            }
        }
        private global::System.String _Order_Customer;
        partial void OnOrder_CustomerChanging(global::System.String value);
        partial void OnOrder_CustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Order_Email
        {
            get
            {
                return _Order_Email;
            }
            set
            {
                OnOrder_EmailChanging(value);
                ReportPropertyChanging("Order_Email");
                _Order_Email = StructuralObject.SetValidValue(value, true, "Order_Email");
                ReportPropertyChanged("Order_Email");
                OnOrder_EmailChanged();
            }
        }
        private global::System.String _Order_Email;
        partial void OnOrder_EmailChanging(global::System.String value);
        partial void OnOrder_EmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Order_Tel
        {
            get
            {
                return _Order_Tel;
            }
            set
            {
                OnOrder_TelChanging(value);
                ReportPropertyChanging("Order_Tel");
                _Order_Tel = StructuralObject.SetValidValue(value, true, "Order_Tel");
                ReportPropertyChanged("Order_Tel");
                OnOrder_TelChanged();
            }
        }
        private global::System.String _Order_Tel;
        partial void OnOrder_TelChanging(global::System.String value);
        partial void OnOrder_TelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Order_TotalMoney
        {
            get
            {
                return _Order_TotalMoney;
            }
            set
            {
                OnOrder_TotalMoneyChanging(value);
                ReportPropertyChanging("Order_TotalMoney");
                _Order_TotalMoney = StructuralObject.SetValidValue(value, "Order_TotalMoney");
                ReportPropertyChanged("Order_TotalMoney");
                OnOrder_TotalMoneyChanged();
            }
        }
        private Nullable<global::System.Double> _Order_TotalMoney;
        partial void OnOrder_TotalMoneyChanging(Nullable<global::System.Double> value);
        partial void OnOrder_TotalMoneyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Order_Date
        {
            get
            {
                return _Order_Date;
            }
            set
            {
                OnOrder_DateChanging(value);
                ReportPropertyChanging("Order_Date");
                _Order_Date = StructuralObject.SetValidValue(value, "Order_Date");
                ReportPropertyChanged("Order_Date");
                OnOrder_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Order_Date;
        partial void OnOrder_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrder_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Order_Note
        {
            get
            {
                return _Order_Note;
            }
            set
            {
                OnOrder_NoteChanging(value);
                ReportPropertyChanging("Order_Note");
                _Order_Note = StructuralObject.SetValidValue(value, true, "Order_Note");
                ReportPropertyChanged("Order_Note");
                OnOrder_NoteChanged();
            }
        }
        private global::System.String _Order_Note;
        partial void OnOrder_NoteChanging(global::System.String value);
        partial void OnOrder_NoteChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_OrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_OrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_OrderDetail object.
        /// </summary>
        /// <param name="orderDetail_ID">Initial value of the OrderDetail_ID property.</param>
        public static N412_OrderDetail CreateN412_OrderDetail(global::System.Int32 orderDetail_ID)
        {
            N412_OrderDetail n412_OrderDetail = new N412_OrderDetail();
            n412_OrderDetail.OrderDetail_ID = orderDetail_ID;
            return n412_OrderDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderDetail_ID
        {
            get
            {
                return _OrderDetail_ID;
            }
            set
            {
                if (_OrderDetail_ID != value)
                {
                    OnOrderDetail_IDChanging(value);
                    ReportPropertyChanging("OrderDetail_ID");
                    _OrderDetail_ID = StructuralObject.SetValidValue(value, "OrderDetail_ID");
                    ReportPropertyChanged("OrderDetail_ID");
                    OnOrderDetail_IDChanged();
                }
            }
        }
        private global::System.Int32 _OrderDetail_ID;
        partial void OnOrderDetail_IDChanging(global::System.Int32 value);
        partial void OnOrderDetail_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderDetail_Product
        {
            get
            {
                return _OrderDetail_Product;
            }
            set
            {
                OnOrderDetail_ProductChanging(value);
                ReportPropertyChanging("OrderDetail_Product");
                _OrderDetail_Product = StructuralObject.SetValidValue(value, "OrderDetail_Product");
                ReportPropertyChanged("OrderDetail_Product");
                OnOrderDetail_ProductChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderDetail_Product;
        partial void OnOrderDetail_ProductChanging(Nullable<global::System.Int32> value);
        partial void OnOrderDetail_ProductChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderDetail_OrderID
        {
            get
            {
                return _OrderDetail_OrderID;
            }
            set
            {
                OnOrderDetail_OrderIDChanging(value);
                ReportPropertyChanging("OrderDetail_OrderID");
                _OrderDetail_OrderID = StructuralObject.SetValidValue(value, "OrderDetail_OrderID");
                ReportPropertyChanged("OrderDetail_OrderID");
                OnOrderDetail_OrderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderDetail_OrderID;
        partial void OnOrderDetail_OrderIDChanging(Nullable<global::System.Int32> value);
        partial void OnOrderDetail_OrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OrderDetail_Quantity
        {
            get
            {
                return _OrderDetail_Quantity;
            }
            set
            {
                OnOrderDetail_QuantityChanging(value);
                ReportPropertyChanging("OrderDetail_Quantity");
                _OrderDetail_Quantity = StructuralObject.SetValidValue(value, "OrderDetail_Quantity");
                ReportPropertyChanged("OrderDetail_Quantity");
                OnOrderDetail_QuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _OrderDetail_Quantity;
        partial void OnOrderDetail_QuantityChanging(Nullable<global::System.Int32> value);
        partial void OnOrderDetail_QuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OrderDetail_Date
        {
            get
            {
                return _OrderDetail_Date;
            }
            set
            {
                OnOrderDetail_DateChanging(value);
                ReportPropertyChanging("OrderDetail_Date");
                _OrderDetail_Date = StructuralObject.SetValidValue(value, "OrderDetail_Date");
                ReportPropertyChanged("OrderDetail_Date");
                OnOrderDetail_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OrderDetail_Date;
        partial void OnOrderDetail_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnOrderDetail_DateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Post object.
        /// </summary>
        /// <param name="post_ID">Initial value of the Post_ID property.</param>
        public static N412_Post CreateN412_Post(global::System.Int32 post_ID)
        {
            N412_Post n412_Post = new N412_Post();
            n412_Post.Post_ID = post_ID;
            return n412_Post;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Post_ID
        {
            get
            {
                return _Post_ID;
            }
            set
            {
                if (_Post_ID != value)
                {
                    OnPost_IDChanging(value);
                    ReportPropertyChanging("Post_ID");
                    _Post_ID = StructuralObject.SetValidValue(value, "Post_ID");
                    ReportPropertyChanged("Post_ID");
                    OnPost_IDChanged();
                }
            }
        }
        private global::System.Int32 _Post_ID;
        partial void OnPost_IDChanging(global::System.Int32 value);
        partial void OnPost_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post_Title
        {
            get
            {
                return _Post_Title;
            }
            set
            {
                OnPost_TitleChanging(value);
                ReportPropertyChanging("Post_Title");
                _Post_Title = StructuralObject.SetValidValue(value, true, "Post_Title");
                ReportPropertyChanged("Post_Title");
                OnPost_TitleChanged();
            }
        }
        private global::System.String _Post_Title;
        partial void OnPost_TitleChanging(global::System.String value);
        partial void OnPost_TitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post_Description
        {
            get
            {
                return _Post_Description;
            }
            set
            {
                OnPost_DescriptionChanging(value);
                ReportPropertyChanging("Post_Description");
                _Post_Description = StructuralObject.SetValidValue(value, true, "Post_Description");
                ReportPropertyChanged("Post_Description");
                OnPost_DescriptionChanged();
            }
        }
        private global::System.String _Post_Description;
        partial void OnPost_DescriptionChanging(global::System.String value);
        partial void OnPost_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post_Detail
        {
            get
            {
                return _Post_Detail;
            }
            set
            {
                OnPost_DetailChanging(value);
                ReportPropertyChanging("Post_Detail");
                _Post_Detail = StructuralObject.SetValidValue(value, true, "Post_Detail");
                ReportPropertyChanged("Post_Detail");
                OnPost_DetailChanged();
            }
        }
        private global::System.String _Post_Detail;
        partial void OnPost_DetailChanging(global::System.String value);
        partial void OnPost_DetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post_Image
        {
            get
            {
                return _Post_Image;
            }
            set
            {
                OnPost_ImageChanging(value);
                ReportPropertyChanging("Post_Image");
                _Post_Image = StructuralObject.SetValidValue(value, true, "Post_Image");
                ReportPropertyChanged("Post_Image");
                OnPost_ImageChanged();
            }
        }
        private global::System.String _Post_Image;
        partial void OnPost_ImageChanging(global::System.String value);
        partial void OnPost_ImageChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AogirishopModel", Name="N412_Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class N412_Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new N412_Product object.
        /// </summary>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        public static N412_Product CreateN412_Product(global::System.Int32 product_ID)
        {
            N412_Product n412_Product = new N412_Product();
            n412_Product.Product_ID = product_ID;
            return n412_Product;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                if (_Product_ID != value)
                {
                    OnProduct_IDChanging(value);
                    ReportPropertyChanging("Product_ID");
                    _Product_ID = StructuralObject.SetValidValue(value, "Product_ID");
                    ReportPropertyChanged("Product_ID");
                    OnProduct_IDChanged();
                }
            }
        }
        private global::System.Int32 _Product_ID;
        partial void OnProduct_IDChanging(global::System.Int32 value);
        partial void OnProduct_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Name
        {
            get
            {
                return _Product_Name;
            }
            set
            {
                OnProduct_NameChanging(value);
                ReportPropertyChanging("Product_Name");
                _Product_Name = StructuralObject.SetValidValue(value, true, "Product_Name");
                ReportPropertyChanged("Product_Name");
                OnProduct_NameChanged();
            }
        }
        private global::System.String _Product_Name;
        partial void OnProduct_NameChanging(global::System.String value);
        partial void OnProduct_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Product_Price
        {
            get
            {
                return _Product_Price;
            }
            set
            {
                OnProduct_PriceChanging(value);
                ReportPropertyChanging("Product_Price");
                _Product_Price = StructuralObject.SetValidValue(value, "Product_Price");
                ReportPropertyChanged("Product_Price");
                OnProduct_PriceChanged();
            }
        }
        private Nullable<global::System.Double> _Product_Price;
        partial void OnProduct_PriceChanging(Nullable<global::System.Double> value);
        partial void OnProduct_PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Product_PriceNew
        {
            get
            {
                return _Product_PriceNew;
            }
            set
            {
                OnProduct_PriceNewChanging(value);
                ReportPropertyChanging("Product_PriceNew");
                _Product_PriceNew = StructuralObject.SetValidValue(value, "Product_PriceNew");
                ReportPropertyChanged("Product_PriceNew");
                OnProduct_PriceNewChanged();
            }
        }
        private Nullable<global::System.Double> _Product_PriceNew;
        partial void OnProduct_PriceNewChanging(Nullable<global::System.Double> value);
        partial void OnProduct_PriceNewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Image
        {
            get
            {
                return _Product_Image;
            }
            set
            {
                OnProduct_ImageChanging(value);
                ReportPropertyChanging("Product_Image");
                _Product_Image = StructuralObject.SetValidValue(value, true, "Product_Image");
                ReportPropertyChanged("Product_Image");
                OnProduct_ImageChanged();
            }
        }
        private global::System.String _Product_Image;
        partial void OnProduct_ImageChanging(global::System.String value);
        partial void OnProduct_ImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Detail
        {
            get
            {
                return _Product_Detail;
            }
            set
            {
                OnProduct_DetailChanging(value);
                ReportPropertyChanging("Product_Detail");
                _Product_Detail = StructuralObject.SetValidValue(value, true, "Product_Detail");
                ReportPropertyChanged("Product_Detail");
                OnProduct_DetailChanged();
            }
        }
        private global::System.String _Product_Detail;
        partial void OnProduct_DetailChanging(global::System.String value);
        partial void OnProduct_DetailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Product_Description
        {
            get
            {
                return _Product_Description;
            }
            set
            {
                OnProduct_DescriptionChanging(value);
                ReportPropertyChanging("Product_Description");
                _Product_Description = StructuralObject.SetValidValue(value, true, "Product_Description");
                ReportPropertyChanged("Product_Description");
                OnProduct_DescriptionChanged();
            }
        }
        private global::System.String _Product_Description;
        partial void OnProduct_DescriptionChanging(global::System.String value);
        partial void OnProduct_DescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Product_Country
        {
            get
            {
                return _Product_Country;
            }
            set
            {
                OnProduct_CountryChanging(value);
                ReportPropertyChanging("Product_Country");
                _Product_Country = StructuralObject.SetValidValue(value, "Product_Country");
                ReportPropertyChanged("Product_Country");
                OnProduct_CountryChanged();
            }
        }
        private Nullable<global::System.Int32> _Product_Country;
        partial void OnProduct_CountryChanging(Nullable<global::System.Int32> value);
        partial void OnProduct_CountryChanged();

        #endregion

    }

    #endregion

}
